### ISSUE TITLE
Navigate to other tab

### ISSUE THREAD

**Issue by greeven** [infokiller/google-search-navigator#11] opened 2017-08-21 02:21 UTC
The readme.md says there are shortcuts for switching to the image/video tab.

That doesn't work yet.

**Comment by infokiller** [comment] 2017-08-21 07:17
Yes, sorry for that, the navigation changes are not released yet (I want to test them more before I release them).

This is a duplicate of #9 so I'm closing it- you can subscribe to #9 to be notified when it's done.

**Closed by infokiller** 2017-08-21 07:17 UTC
